stages:
  - test
  - deploy

test:debian_bullseye:
  stage: test
  image: debian:bullseye
  script:
    - ./setup.sh --skip-config --no-prompt

test:debian_bookworm:
  stage: test
  image: debian:bookworm
  script:
    - ./setup.sh --skip-config --no-prompt

test:ubuntu_jammy:
  stage: test
  image: ubuntu:22.04
  script:
    - ./setup.sh --skip-config --no-prompt

test:arch_linux:
  stage: test
  image: archlinux:latest
  script:
    - ./setup.sh --skip-config --no-prompt

test:manjaro_linux:
  stage: test
  image: manjarolinux/base:latest
  script:
    - ./setup.sh --skip-config --no-prompt

test:rocky_linux:
  stage: test
  image: rockylinux/rockylinux:8.6
  script:
    - ./setup.sh --skip-config --no-prompt

test:oracle_linux:
  stage: test
  image: oraclelinux:9.1
  script:
    - ./setup.sh --skip-config --no-prompt

test:amazon_linux:
  stage: test
  image: amazonlinux:latest
  script:
    - ./setup.sh --skip-config --no-prompt

test:alpine:
  stage: test
  image: alpine:latest
  script:
    - apk add --no-cache bash
    - ./setup.sh --skip-config --no-prompt

tagging:
  image: node:18-alpine
  stage: deploy
  allow_failure: true
  before_script:
    - apk add git
  script:
    - git config --global user.name metahkg-bot
    - git config --global user.email bot@metahkg.org
    - tag=$(node -e "console.log(require('./package.json').version)")
    - if [ $CI_COMMIT_BRANCH = "dev" ]; then tag=${tag}-dev; fi;
    - git tag "$tag"
    - git push https://root:$gitlab_token@$CI_SERVER_HOST/$CI_PROJECT_PATH.git $tag
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_AUTHOR != "metahkg-bot <bot@metahkg.org>" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master")
      changes:
        - package.json

include:
  - template: Auto-DevOps.gitlab-ci.yml
