version: '3.2'
services:
  web:
    container_name: web
    build:
      context: ../metahkg-web
      dockerfile: ./Dockerfile
      args:
        REACT_APP_recaptchasitekey: ${REACT_APP_recaptchasitekey}
    tty: true
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    restart: always
    environment:
      port: ${WEB_PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - server
      - mongo
    networks:
      - metahkg-network
  server:
    container_name: server
    build:
      context: ../metahkg-server
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${port}:${port}
    restart: always
    environment:
      DB_URI: ${DB_URI}
      mailgun_key: ${mailgun_key}
      domain: ${domain}
      port: ${port}
      recaptchasecret: ${recaptchasecret}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo
    networks:
      - metahkg-network
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --auth --port=${MONGO_PORT} --bind_ip_all
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data:/data/db
    networks:
      - metahkg-network
networks:    
  metahkg-network:
    external: true
