services:
  metahkg-nginx:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-nginx
    image: metahkg${COMPOSE_PROJECT_NAME}/nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${PORT:-$port}:80
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    environment:
      METAHKG_LINKS_NAME: metahkg${COMPOSE_PROJECT_NAME}-links
      METAHKG_SERVER_NAME: metahkg${COMPOSE_PROJECT_NAME}-server
      METAHKG_WEB_NAME: metahkg${COMPOSE_PROJECT_NAME}-web
      METAHKG_IMAGES_NAME: metahkg${COMPOSE_PROJECT_NAME}-images
      METAHKG_IMGPUSH_NAME: metahkg${COMPOSE_PROJECT_NAME}-imgpush
      METAHKG_RLP_PROXY_NAME: metahkg${COMPOSE_PROJECT_NAME}-rlp-proxy
      DOMAIN: ${DOMAIN:-$domain}
      LINKS_DOMAIN: ${LINKS_DOMAIN}
      IMAGES_DOMAIN: ${IMAGES_DOMAIN}
      RLP_PROXY_DOMAIN: ${RLP_PROXY_DOMAIN}
    depends_on:
      - metahkg-server
      - metahkg-web
      - metahkg-links
      - metahkg-images
      - metahkg-rlp-proxy
    networks:
      - metahkg-network
  metahkg-web:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-web
    image: registry.gitlab.com/metahkg/metahkg-web/${branch:-master}:${version:-latest}
    build:
      context: ../metahkg-web
      dockerfile: ./Dockerfile
      args:
        REACT_APP_recaptchasitekey: ${RECAPTCHA_SITE_KEY:-$REACT_APP_recaptchasitekey}
        REACT_APP_IMAGES_DOMAIN: ${IMAGES_DOMAIN}
        REACT_APP_RLP_PROXY_DOMAIN: ${RLP_PROXY_DOMAIN}
        REACT_APP_build: ${REACT_APP_build}
        REACT_APP_version: ${REACT_APP_version}
        REACT_APP_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
        env: ${env}
    tty: true
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    environment:
      PORT: 3002
      env: ${env}
      REACT_APP_recaptchasitekey: ${RECAPTCHA_SITE_KEY:-$REACT_APP_recaptchasitekey}
      REACT_APP_IMAGES_DOMAIN: ${IMAGES_DOMAIN}
      REACT_APP_RLP_PROXY_DOMAIN: ${RLP_PROXY_DOMAIN}
      REACT_APP_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      GCM_SENDER_ID: ${GCM_SENDER_ID}
    volumes:
      - ../metahkg-web/src:/app/src
      - ../metahkg-web/tailwind.config.js:/app/tailwind.config.js
      - ../metahkg-web/public:/app/public
    depends_on:
      - metahkg-server
      - metahkg-links
      - metahkg-images
      - metahkg-rlp-proxy
    networks:
      - metahkg-network
  metahkg-server:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-server
    image: registry.gitlab.com/metahkg/metahkg-server/${branch:-master}:${version:-latest}
    build:
      context: ../metahkg-server
      dockerfile: ./Dockerfile
      args:
        env: ${env}
    tty: true
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@metahkg${COMPOSE_PROJECT_NAME}-mongo:${MONGO_PORT}
      REDIS_HOST: metahkg${COMPOSE_PROJECT_NAME}-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      LINKS_DOMAIN: ${LINKS_DOMAIN}
      MAILGUN_KEY: ${MAILGUN_KEY:-$mailgun_key}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN:-$mailgun_domain}
      DOMAIN: ${DOMAIN:-$domain}
      PORT: 3001
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET:-$recaptchasecret}
      CORS: ${CORS:-$cors}
      env: ${env}
      REGISTER_MODE: ${REGISTER_MODE:-$register}
      REGISTER_DOMAINS: ${REGISTER_DOMAINS}
      VISIBILITY: ${VISIBILITY}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      GCM_API_KEY: ${GCM_API_KEY}
      KEY_PASSPHRASE: ${KEY_PASSPHRASE}
    volumes:
      - ./images:/app/images:Z
      - ./certs:/app/certs:Z
      - ../metahkg-server/src:/app/src
    depends_on:
      - metahkg-mongo
      - metahkg-redis
    networks:
      - metahkg-network
  metahkg-links:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-links
    image: registry.gitlab.com/metahkg/metahkg-links/${branch:-master}:${version:-latest}
    build:
      context: ../metahkg-links
      dockerfile: ./Dockerfile
    tty: true
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    environment:
      PORT: 3003
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@metahkg${COMPOSE_PROJECT_NAME}-mongo:${MONGO_PORT}
      metahkgDomain: ${DOMAIN:-$domain}
    networks:
      - metahkg-network
    depends_on:
      - metahkg-mongo
  metahkg-imgpush:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-imgpush
    image: registry.gitlab.com/metahkg/forks/imgpush:latest
    tty: true
    restart: always
    environment:
      PORT: 3006
      IMAGES_DIR: /images/
      CACHE_DIR: /cache/
      MAX_UPLOADS_PER_DAY: 300
      MAX_UPLOADS_PER_HOUR: 100
      MAX_UPLOADS_PER_MINUTE: 20
      ALLOWED_ORIGINS: "['https://${DOMAIN:-$domain}']"
      NAME_STRATEGY: randomstr
      MAX_TMP_FILE_AGE: "5 * 60"
      RESIZE_TIMEOUT: 5
      JWT_PUBLIC_KEY: /certs/public.pem
      JWT_ALGORITHM: EdDSA
      UPLOAD_REQUIRE_AUTH: "True"
      GET_REQUIRE_AUTH: "False"
      DISABLE_RESIZE: "True"
      DISABLE_URL_UPLOAD: "True"
      UPLOAD_ROUTE: "/upload"
      IMAGES_ROOT: "/images"
      MAX_SIZE_MB: 2
    mem_limit: 500mb
    memswap_limit: 500mb
    networks:
      - metahkg-network
    volumes:
      - ./imgpush:/images
      - ./certs:/certs
    depends_on:
      - metahkg-server
  metahkg-images:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-images
    image: registry.gitlab.com/metahkg/forks/imageproxy:latest
    tty: true
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    entrypoint: "/app/imageproxy -addr 0.0.0.0:3004 -cache /tmp/imageproxy"
    networks:
      - metahkg-network
    volumes:
      - ./imageproxy:/tmp/imageproxy:Z
  metahkg-rlp-proxy:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-rlp-proxy
    image: registry.gitlab.com/metahkg/rlp-proxy-rewrite/${branch:-master}:${version:-latest}
    build:
      context: ../rlp-proxy-rewrite
      dockerfile: ./Dockerfile
      args:
        env: ${env}
    tty: true
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@metahkg${COMPOSE_PROJECT_NAME}-mongo:${MONGO_PORT}
      REDIS_HOST: metahkg${COMPOSE_PROJECT_NAME}-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PORT: 3005
      NO_HEADLESS: "false"
      env: ${env}
    depends_on:
      - metahkg-mongo
      - metahkg-redis
    networks:
      - metahkg-network
    volumes:
      - ../rlp-proxy-rewrite/src:/app/src
  metahkg-mongo:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-mongo
    image: mongo:latest
    tty: true
    command: mongod --auth --port=${MONGO_PORT} --bind_ip_all
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: metahkg
    networks:
      - metahkg-network
    volumes:
      - ./data:/data/db
      - ../mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  metahkg-redis:
    image: redis:alpine
    container_name: metahkg${COMPOSE_PROJECT_NAME}-redis
    command: redis-server --save 10 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: always
    mem_limit: 500mb
    memswap_limit: 500mb
    ports:
      - ${REDIS_PORT}:6379
    networks:
       - metahkg-network
    volumes:
      - ./redis_data:/data
networks:
  metahkg-network:
    driver: bridge
