version: '3.2'
services:
  metahkg-web:
    container_name: metahkg${DOCKER_PREFIX}-web
    build:
      context: ../metahkg-web
      dockerfile: ./Dockerfile
      args:
        REACT_APP_recaptchasitekey: ${REACT_APP_recaptchasitekey}
    tty: true
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    restart: always
    environment:
      port: ${WEB_PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - metahkg-server
      - metahkg-links
    networks:
      - metahkg-network
  metahkg-server:
    container_name: metahkg${DOCKER_PREFIX}-server
    build:
      context: ../metahkg-server
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${port}:${port}
    restart: always
    environment:
      DB_URI: ${DB_URI}
      LINKS_DOMAIN: ${LINKS_DOMAIN}
      mailgun_key: ${mailgun_key}
      domain: ${domain}
      port: ${port}
      recaptchasecret: ${recaptchasecret}
      jwtKey: ${jwtKey}
    volumes:
      - ./images:/usr/src/app/images
      - ./src:/usr/src/app/src
    depends_on:
      - metahkg-mongo
    networks:
      - metahkg-network
  metahkg-links:
    container_name: metahkg${DOCKER_PREFIX}-links
    build:
      context: ../metahkg-links
      dockerfile: ./Dockerfile
    tty: true
    restart: always
    ports:
      - ${LINKS_PORT}:${LINKS_PORT}
    environment:
      port: ${LINKS_PORT}
      DB_URI: ${DB_URI}
      metahkgDomain: ${domain}
    networks:
      - metahkg-network
    depends_on:
      - metahkg-mongo
  metahkg-mongo:
    container_name: metahkg${DOCKER_PREFIX}-mongo
    image: mongo
    command: mongod --auth --port=${MONGO_PORT} --bind_ip_all
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: metahkg
    volumes:
      - ./data:/data/db
    networks:
      - metahkg-network
networks:    
  metahkg-network:
    external: true
