
services:
  server:
    container_name: server
    build:
      context: ../metahkg-server
      dockerfile: ../metahkg-server/Dockerfile
    tty: true
    ports:
      - 3000:3000
    environment:
      DB_URI: ${DB_URI}
      mailgun_key: ${mailgun_key}
      domain: ${domain}
      port: ${port}
      recaptchasecret: ${recaptchasecret}
      awsRegion: ${awsRegion}
      s3Bucket: ${s3Bucket}
    volumes:
      - ../metahkg-server/src:/usr/src/app/src
    depends_on:
      - DB
      - redis
  mongo:
    container_name: metahkg-mongo
    image: mongo
    command: mongod --port ${MONGO_PORT};
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 18081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/