services:
  metahkg-nginx:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-nginx
    image: metahkg${COMPOSE_PROJECT_NAME}/nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${PORT:-$port}:80
    restart: always
    environment:
      METAHKG_LINKS_NAME: metahkg${COMPOSE_PROJECT_NAME}-links
      METAHKG_SERVER_NAME: metahkg${COMPOSE_PROJECT_NAME}-server
      METAHKG_WEB_NAME: metahkg${COMPOSE_PROJECT_NAME}-web
      METAHKG_IMAGES_NAME: metahkg${COMPOSE_PROJECT_NAME}-images
      METAHKG_RLP_PROXY_NAME: metahkg${COMPOSE_PROJECT_NAME}-rlp-proxy
      DOMAIN: ${DOMAIN:-$domain}
      LINKS_DOMAIN: ${LINKS_DOMAIN}
      IMAGES_DOMAIN: ${IMAGES_DOMAIN}
      RLP_PROXY_DOMAIN: ${RLP_PROXY_DOMAIN}
    depends_on:
      - metahkg-server
      - metahkg-web
      - metahkg-links
      - metahkg-images
      - metahkg-rlp-proxy
    networks:
      - metahkg-network
  metahkg-web:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-web
    image: registry.gitlab.com/metahkg/metahkg-web/${branch:-master}:${version:-latest}
    build:
      context: ../metahkg-web
      dockerfile: ./Dockerfile
      args:
        REACT_APP_recaptchasitekey: ${RECAPTCHA_SITE_KEY:-$REACT_APP_recaptchasitekey}
        REACT_APP_IMAGES_DOMAIN: ${IMAGES_DOMAIN}
        REACT_APP_RLP_PROXY_DOMAIN: ${RLP_PROXY_DOMAIN}
        REACT_APP_build: ${REACT_APP_build}
        REACT_APP_version: ${REACT_APP_version}
        REACT_APP_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
        env: ${env}
    tty: true
    restart: always
    environment:
      PORT: 3002
      env: ${env}
      REACT_APP_recaptchasitekey: ${RECAPTCHA_SITE_KEY:-$REACT_APP_recaptchasitekey}
      REACT_APP_IMAGES_DOMAIN: ${IMAGES_DOMAIN}
      REACT_APP_RLP_PROXY_DOMAIN: ${RLP_PROXY_DOMAIN}
      REACT_APP_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      GCM_SENDER_ID: ${GCM_SENDER_ID}
    volumes:
      - ../metahkg-web/src:/app/src
      - ../metahkg-web/tailwind.config.js:/app/tailwind.config.js
      - ../metahkg-web/public:/app/public
    depends_on:
      - metahkg-server
      - metahkg-links
      - metahkg-images
      - metahkg-rlp-proxy
    networks:
      - metahkg-network
  metahkg-server:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-server
    image: registry.gitlab.com/metahkg/metahkg-server/${branch:-master}:${version:-latest}
    build:
      context: ../metahkg-server
      dockerfile: ./Dockerfile
      args:
        env: ${env}
    tty: true
    restart: always
    environment:
      DB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@metahkg${COMPOSE_PROJECT_NAME}-mongo:${MONGO_PORT}
      LINKS_DOMAIN: ${LINKS_DOMAIN}
      MAILGUN_KEY: ${MAILGUN_KEY:-$mailgun_key}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN:-$mailgun_domain}
      DOMAIN: ${DOMAIN:-$domain}
      PORT: 3001
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET:-$recaptchasecret}
      CORS: ${CORS:-$cors}
      env: ${env}
      REGISTER_MODE: ${REGISTER_MODE:-$register}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      GCM_API_KEY: ${GCM_API_KEY}
      KEY_PASSPHRASE: ${KEY_PASSPHRASE}
    volumes:
      - ./images:/app/images:Z
      - ./certs:/app/certs:Z
      - ../metahkg-server/src:/app/src
    depends_on:
      - metahkg-mongo
    networks:
      - metahkg-network
  metahkg-links:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-links
    image: registry.gitlab.com/metahkg/metahkg-links/${branch:-master}:${version:-latest}
    build:
      context: ../metahkg-links
      dockerfile: ./Dockerfile
    tty: true
    restart: always
    environment:
      PORT: 3003
      DB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@metahkg${COMPOSE_PROJECT_NAME}-mongo:${MONGO_PORT}
      metahkgDomain: ${DOMAIN:-$domain}
    networks:
      - metahkg-network
    depends_on:
      - metahkg-mongo
  metahkg-images:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-images
    image: ghcr.io/willnorris/imageproxy:latest
    tty: true
    restart: always
    entrypoint: "/app/imageproxy -addr 0.0.0.0:3004 -cache /tmp/imageproxy"
    networks:
      - metahkg-network
    volumes:
      - ./imageproxy:/tmp/imageproxy:Z
  metahkg-rlp-proxy:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-rlp-proxy
    image: registry.gitlab.com/metahkg/rlp-proxy-rewrite/${branch:-master}:${version:-latest}
    build:
      context: ../rlp-proxy-rewrite
      dockerfile: ./Dockerfile
    tty: true
    restart: always
    environment:
      DB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@metahkg${COMPOSE_PROJECT_NAME}-mongo:${MONGO_PORT}
      PORT: 3005
    depends_on:
      - metahkg-mongo
    networks:
      - metahkg-network
  metahkg-mongo:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-mongo
    image: mongo:latest
    tty: true
    command: mongod --auth --port=${MONGO_PORT} --bind_ip_all
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: metahkg
    networks:
      - metahkg-network
    volumes:
      - ./data:/data/db
      - ../mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  metahkg-mongo-express:
    container_name: metahkg${COMPOSE_PROJECT_NAME}-mongo-express
    image: mongo-express:latest
    tty: true
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      ME_CONFIG_MONGODB_SERVER: metahkg${COMPOSE_PROJECT_NAME}-mongo
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_AUTH_DATABASE: metahkg
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - metahkg-network
networks:
  metahkg-network:
    driver: bridge
