
services:
  server:
    container_name: server
    build:
      context: ../metahkg-server
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${port}:${port}
    environment:
      DB_URI: ${DB_URI}
      mailgun_key: ${mailgun_key}
      domain: ${domain}
      port: ${port}
      recaptchasecret: ${recaptchasecret}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo
  mongo:
    container_name: metahkg-mongo
    image: mongo
    command: mongod --auth --port=${MONGO_PORT}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 18081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/
